<?php

$plugin = array(
  'title' => t('Home Layout'),
  'icon' => 'home-layout.png',
  'category' => t('DPF'),
  'theme' => 'home-layout',
  'regions' => array(
    'header' => t('Header'),
    'first' => t('First'),
    'second' => t('Second'),
    'third' => t('Third'),
    'fourth' => t('Fourth'),
    'video' => t('Featured Video'),
    'fifth' => t('Fifth'),
    'sixth' => t('Sixth'),
    'seventh' => t('Seventh'),
    'eighth' => t('Eighth'),
    'ninth' => t('Ninth'),
    'tenth' => t('Tenth'),
  ),
);
