<?php

/**
* @file
* A module that provides a css file within the admin theme.
*/

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function admin_css_help($path, $arg) {
  switch ($path) {
    case "admin/help#admin_css":
      return '<p>' . t("Provides a css file for the admin theme.") . '</p>';
      break;
  }
}

drupal_add_css(drupal_get_path('module', 'admin_css') . '/admin_css.css');
